### ISSUE TITLE
Ctrl-A not working

### ISSUE THREAD

**Issue by perrycate** [seanyeh/vibreoffice#12]
Occasionally I have to change the font size or something for the document as a whole, and I'm in the habit of just pressing Ctrl-A to select everything. With Vibreoffice enabled, Pressing Ctrl-A simply moves the cursor to the top of the document after what I can only describe as a strange flicker onscreen. This might just be an unavoidable conflict, but I don't think Ctrl-A does anything in Vim. (That I can think of at least.)

**Comment by seanyeh** [comment]
Hi, thanks for pointing this out. The reason for this was that Ctrl-a was selecting all as expected, but since it was in normal mode, the cursor immediately returned to highlight only one character.
I hardcoded Ctrl-a as a shortcut that changes the mode into visual, which solves this problem
