### ISSUE TITLE
"u" should be mapped to Ctrl-Z

### ISSUE THREAD

**Issue by perrycate** [seanyeh/vibreoffice#13]
I make mistakes a lot, so this was one of the first things I noticed...

**Comment by arnaldorusso** [comment]
This feature would be very nice to see!
BTW, thanks for deving this such a great tool! 
I hava always to use Libreoffice, and always typing 'jjjjj' is really anoying! Now at least this problem is solved to me! :+1:

**Comment by seanyeh** [comment]
Thanks for pointing this out. I just added undo/redo functionality with u and C-r.
