### ISSUE TITLE
Error thrown when building extension.

### ISSUE THREAD

**Issue by perrycate** [seanyeh/vibreoffice#15]
Console output:
http://pastebin.com/GmkhqRmz

Build still appears to work fine, but the error is misleading, and clearly something isn't working right.

**Comment by seanyeh** [comment]
Are you on OS X? basename on Linux (from GNU coreutils) has an option to specify the suffix with the "-s" flag. Apparently it's non-standard so I fixed that. Thanks for pointing it out.

**Comment by perrycate** [comment]
I'm on Linux, the machine I noticed this on was running Debian 7, coreutils was version 8.13. I'm on Debian Stable, so it would not surprise me one bit if the coreutils package is archaic compared to whatever the current version is and possibly missing some flags.
