### ISSUE TITLE
visual mode does not select anything with arrow keys

### ISSUE THREAD

**Issue by fdietze** [seanyeh/vibreoffice#20]

**Comment by seanyeh** [comment]
Thanks for pointing that out. This should be an easy fix. I'll try to take a look at it when I have time, or feel free to dig in the source yourself.

**Comment by arnaldorusso** [comment]
Just complementing the issue, when in visual mode, the `End` key does not work as well.
@seanyeh could you point out where specifically the code should be fixed?
Cheers,
Arnaldo.

**Comment by seanyeh** [comment]
Thanks for pointing that out. I think it should be fixed now, hopefully!
