### ISSUE TITLE
Annotation insertion error.

### ISSUE THREAD

**Issue by arnaldorusso** [seanyeh/vibreoffice#21]
While trying to insert an Annotation, it returns the following error:

BASIC runtime error!
Type: com.sun.star.uno.RuntimeException
Message: no text selection.

This is the excert of the code where it seems to crash.

```
' -----------
' Singletons
' -----------
Function getCursor
    getCursor = VIEW_CURSOR
End Function

Function getTextCursor
    dim oTextCursor
    oTextCursor = getCursor().getText.createTextCursorByRange(getCursor())
    ' oTextCursor.gotoRange(oTextCursor.getStart(), False)

    getTextCursor = oTextCursor
End Function
```

**Comment by seanyeh** [comment]
Thanks for letting me know. I will put this on the queue

**Comment by seanyeh** [comment]
My solution is to disable vibreoffice temporarily when doing an annotation. From what I can tell, I don't think it's possible to have it work with annotations.
