### ISSUE TITLE
Is working vibreoffice on linux ?

### ISSUE THREAD

**Issue by i5513** [seanyeh/vibreoffice#4]
Hello,

I have libreoffice from Debian Sid, and I installed your extension. But I'm not sure how get it working.

How do you flip from insert mode to normal mode ? In my installation no key has changed its behaviour

Thank you developping such extension !

**Comment by i5513** [comment]
Hello,

It was an chrome issue. After closing chrome (browser where I downloaded the extension) and restarting lowriter, it is working.

I would like to see : "/", "gg", "^" features :)

Thank you !

**Comment by seanyeh** [comment]
Thanks for your interest in this project! I have been really busy so unfortunately have not had any time to work on vibreoffice. Searching ("/") is a huge priority for me, so that is something I will try to get to when I can. Feel free to submit a pull request too!
